### PR TITLE
Add .fsc script for Xperia XZ and XP 7.1 firmwares

### PR DESCRIPTION
**Pull request by hazuki0x0**

### CODE REVIEW

**Comment by santiagom9992** [comment]
Are you sure this is the new FSC script for the new firmware 41.2 Firmware??
I compare all the lines with the previous 39.fsc, and it has the same lines.

You already test it flashing your phone successfully??

**Comment by hazuki0x0** [comment]
I flashed my XZ, and it's working.

**Comment by santiagom9992** [comment]
I try to flash my phone using this script and is not working. I get a lot of errors trying to flash

**Comment by championswimmer** [comment]
works for me too

**Comment by algorban** [comment]
Simulated flashing the latest firmware for my XP with the given file. Here is the log file. warnings confuse me.

[flashtool_2017-05-06_12-29-28.txt](https://github.com/Androxyde/devices/files/981041/flashtool_2017-05-06_12-29-28.txt)

**Pull request merged**
